### ISSUE TITLE
[BUG] Invite to Org Form

### ISSUE THREAD

**Issue by Akshu-on-github** [Py-Contributors/support#8]
In the `Invite to Organization` template, the questions and meta data has the details of the organisation that created it (EddieHub)
I'd like to create a PR to fix the same

**Comment by codePerfectPlus** [comment]
@Akshu-on-github Yes sure

**Comment by codePerfectPlus** [comment]
I am not sure, if it will count for hack squad or not.

**Comment by Akshu-on-github** [comment]
I don't see a reason why shouldn't, but even if it isn't, I'd like to go ahead with working on it if it adds value 😅
